// Downsized copies generated by scripts/make-responsive-images.py (keep widths in sync).
// Each entry: available widths, plus the original's own width as the largest candidate.
const VARIANTS: Record<string, { widths: number[]; original: number }> = {
  '/IMG-20260921-WA0021.jpg': { widths: [600, 900, 1200], original: 1600 },
  '/IMG-20260923-WA0016.jpg': { widths: [600, 900], original: 1066 },
  '/IMG-20260923-WA0015.jpg': { widths: [600, 900], original: 1600 },
  '/IMG-20260923-WA0019.jpg': { widths: [600, 900], original: 1200 },
  '/IMG-20260923-WA0018.jpg': { widths: [600, 900], original: 1600 },
  '/IMG-20260923-WA0040.jpg': { widths: [600, 900], original: 1320 },
  '/IMG-20260923-WA0013(1).jpg': { widths: [600, 900], original: 1600 },
  '/IMG-20260921-WA0033.jpg': { widths: [800, 1200], original: 1600 },
  '/mechanic3.webp': { widths: [1200], original: 2200 },
  '/mechanic3.avif': { widths: [1200], original: 2200 },
};

const variant = (path: string, w: number) => path.replace(/(\.[a-z0-9]+)$/i, `-${w}$1`);

/** srcset string for a public image, or undefined if it has no downsized copies. */
export function srcSetFor(path: string): string | undefined {
  const v = VARIANTS[path];
  if (!v) return undefined;
  return [...v.widths.map((w) => `${variant(path, w)} ${w}w`), `${path} ${v.original}w`].join(', ');
}
